blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Website
    url: https://whomine.net/
    about: Check out our website
  - name: ğŸ“– Docs
    url: https://docs.whomine.net/
    about: Could be useful for basic player questions
  - name: ğŸ’¬ Discord
    url: https://discord.whomine.net/
    about: Join our Discord server, questions are answered faster here
