blank_issues_enabled: false
contact_links:
  - name: Issue with localization
    url: https://github.com/MinersStudios/WMConfig/issues/new/choose
    about: Please open issues relating to localization in MinersStudios/WMConfig
  - name: ğŸŒ Website
    url: https://whomine.net/
    about: Check out our website
  - name: ğŸ“– Docs
    url: https://docs.whomine.net/
    about: Could be useful for basic player questions
  - name: ğŸ’¬ Discord
    url: https://discord.whomine.net/
    about: Join our Discord server, questions are answered faster here
